### ISSUE TITLE
Turning off debug output

### ISSUE THREAD

**Issue by ticklemynausea** [godong9/solr-node#45]
Hi. I would like to turn off the debug output in non-development environments but looking into the source I found no obvious way of doing so.

Any suggestions?

**Comment by godong9** [comment]
Oh, that is not supported yet... 

I will add that setting option to 1.0.2.

Thanks to reporting this issue.

**Comment by godong9** [comment]
Update completed!

**Comment by ticklemynausea** [comment]
Thanks very much!
