### ISSUE TITLE
Please, publish a new version to npm

### ISSUE THREAD

**Issue by carstenhag** [godong9/solr-node#69]
Experienced a bug caused by the following, now outdated lines.  
See https://github.com/godong9/solr-node/pull/64/commits/79d72edb3198f6011f6b644bbf579dcf402f8f75 for the change where this bug was fixed.

```js
    try {
      result = JSON.parse(body);
      return finalCallback(null, result);
    } catch(e) {
      return finalCallback(null, body);
    }
```

After parsing the body, the callback is returned. If there's an error in `finalCallback`, the method catches the exception but returns another callback.

PR #64 fixed this bug. Could you please submit a new version of this package to npm?

**Comment by godong9** [comment]
Sorry, I forgot that. Today, I will publish new version.

**Comment by godong9** [comment]
Publish completed!
