### ISSUE TITLE
solr Basic Auth

### ISSUE THREAD

**Issue by lvenier** [godong9/solr-node#80]
It is possible to setup Basic Authentication with Sorl : 
https://lucene.apache.org/solr/guide/7_6/basic-authentication-plugin.html

The auth login/passwor should be added when creating the client:

var client = new SolrNode({
    host: '127.0.0.1',
    port: '8983',
    core: 'test',
    protocol: 'http',
    user: 'cool',
    password: 'reallycool'
});

**Comment by lvenier** [comment]
made a proposal through https://github.com/godong9/solr-node/pull/81

**Comment by lvenier** [comment]
Any chance to have it considered ?

**Comment by godong9** [comment]
This feature is breaking changes.
Need to consider backwards compatibility.

**Comment by lvenier** [comment]
Added to 1.2.1.
juste npm update on my application and ti's all good for me.

Thanks.
